# Imports

Nesta seção são importadas as bibliotecas necessárias para:
- carregar e manipular dados (`pandas`, `numpy`);
- plotar gráficos (`matplotlib`);
- criar e avaliar modelos de regressão (`sklearn`).

In [69]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import linear_model as lm
from sklearn.ensemble import RandomForestRegressor
from sklearn import tree as tr
from sklearn import metrics as mt
from sklearn import preprocessing as pp

from sklearn.metrics import auc
from sklearn.metrics import roc_curve, roc_auc_score

# Dataset

Neste bloco são carregados os conjuntos de dados de treino, validação e teste.
Os dados são lidos de arquivos CSV separados para manter o processo de avaliação correto.

In [70]:
# Dataset
# Carregando dados de treinamento/classificação
X_train =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_treinamento/X_training.csv')
y_train =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_treinamento/y_training.csv')

# Carregando dados de validação/classificação
X_val =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_validacao/X_validation.csv')
y_val =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_validacao/y_validation.csv')

# Carregando dados de teste/Classificação
X_test =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_teste/X_test.csv')
y_test =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_teste/y_test.csv')

In [71]:
X_train.head()

,id,customer_type,age,class,flight_distance,inflight_wifi_service,departure_arrival_time_convenient,ease_of_online_booking,gate_location,food_and_drink,...,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,gender_Female,gender_Male,type_of_travel_business_travel,type_of_travel_personal_travel
0,13508,1,0.500000,0.0,0.039580,0.6,0.6,0.6,0.6,1.0,...,0.5,1.00,0.6,0.4,0.000000,0.013848,1.0,0.0,1.0,0.0
1,28874,1,0.243590,0.0,0.205775,0.6,0.4,0.4,0.4,0.6,...,0.5,0.50,0.2,0.6,0.000000,0.000000,0.0,1.0,1.0,0.0
2,21484,0,0.435897,1.0,0.026858,0.6,0.6,0.6,0.2,1.0,...,0.0,1.00,0.6,1.0,0.000000,0.000000,1.0,0.0,1.0,0.0
3,48280,1,0.589744,0.5,0.041397,0.6,1.0,0.6,0.6,0.8,...,0.0,1.00,0.4,0.4,0.029499,0.020772,1.0,0.0,0.0,1.0
4,472,0,0.423077,1.0,0.016559,0.2,0.2,0.2,0.8,0.6,...,1.0,0.75,0.8,0.6,0.021632,0.019782,0.0,1.0,1.0,0.0

# Training

Nesta seção é feita a comparação entre vários modelos de regressão.
Cada algoritmo será treinado e avaliado usando métricas de desempenho.

In [10]:
# Algoritmos: 
# Linear Regression, Decision Tree Regressor, Random Forest Regressor, 
# Polinomial Regression, Linear Regression Lasso, Linear Regression Ridge, Linear Regression Elastic Net,
# Polinomial Regression Lasso, Polinomial Regression Ridge e Polinomial Regression Elastic Net
# Métricas de performance: R2, MSE, RMSE, MAE e MAPE

## Linear Regression

Neste bloco é treinado um modelo de regressão linear simples usando os dados de treino. Depois o modelo é validado com os dados de validação e por fim são somados os datasets de treinamento e validação, para criar um modelo final que será testado com os dados de teste.
Em seguida são calculadas métricas de desempenho para avaliar a qualidade do ajuste.

In [11]:
# Model Training
lr_model = LinearRegression()
lr_model.fit( X_train, y_train )

LinearRegression()

In [12]:
#Previsão sobre os dados de treinamento
y_pred_train = lr_model.predict( X_train )
# # R²
r2_squared_train = mt.r2_score(y_train, y_pred_train)
print("R²:", r2_squared_train)
# MSE 
mse_train = mt.mean_squared_error(y_train, y_pred_train)
print("MSE", mse_train)
# RMSE
rmse_train = np.sqrt(mse_train)
print("RMSE", rmse_train)
# MAE
mae_train = mt.mean_absolute_error(y_train, y_pred_train)
print("MAE", mae_train)
# MAPE
y_train_flat = y_train.values.ravel()
y_pred_train_flat = y_pred_train.ravel()

mask = y_train_flat != 0
mape_train = np.mean(
    np.abs((y_train_flat[mask] - y_pred_train_flat[mask]) / y_train_flat[mask])
)
print("MAPE", mape_train)

R²: 0.553549636106226
MSE 0.1096323327773033
RMSE 0.3311077359067639
MAE 0.24902069470379487
MAPE 0.2667823292751459

In [14]:
#Previsão sobre os dados de validação
y_pred_val = lr_model.predict( X_val )
# # R²
r2_squared_val = mt.r2_score(y_val, y_pred_val)
print("R²:", r2_squared_val)
# MSE 
mse_val = mt.mean_squared_error(y_val, y_pred_val)
print("MSE", mse_val)
# RMSE
rmse_val = np.sqrt(mse_val)
print("RMSE", rmse_val)
# MAE
mae_val = mt.mean_absolute_error(y_val, y_pred_val)
print("MAE", mae_val)
# MAPE
y_val_flat = y_val.values.ravel()
y_pred_val_flat = y_pred_val.ravel()

mask = y_val_flat != 0
mape_val = np.mean(
    np.abs((y_val_flat[mask] - y_pred_val_flat[mask]) / y_val_flat[mask])
)
print("MAPE", mape_val)

R²: 0.547778744051949
MSE 0.11104822157725189
RMSE 0.33323898568032506
MAE 0.24996851952487667
MAPE 0.2667823292751459

In [13]:
#Agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
model_last_lr = LinearRegression()
model_last_lr.fit( np.concatenate( (X_train, X_val) ), np.concatenate((y_train, y_val)) )

LinearRegression()

In [15]:
# Modelo validado com os dados de teste e treinada com os dados de treinamento e validação juntos
#Previsão sobre os dados de teste
y_pred_test = model_last_lr.predict( X_test )
# # R²
r2_squared_test = mt.r2_score(y_test, y_pred_test)
print("R²:", r2_squared_test)
# MSE 
mse_test = mt.mean_squared_error(y_test, y_pred_test)
print("MSE", mse_test)
# RMSE
rmse_test = np.sqrt(mse_test)
print("RMSE", rmse_test)
# MAE
mae_test = mt.mean_absolute_error(y_test, y_pred_test)
print("MAE", mae_test)
# MAPE
y_test_flat_dt = y_test.values.ravel()
y_pred_test_dt = y_pred_test.ravel()

mask = y_test_flat_dt != 0
mape_test = np.mean(
    np.abs((y_test_flat_dt[mask] - y_pred_test_dt[mask]) / y_test_flat_dt[mask])
)
print("MAPE", mape_test)

R²: 0.5495195462189956
MSE 0.11093957055194692
RMSE 0.3330759231045482
MAE 0.24996953954986162
MAPE 0.26836840685249835

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

## Decision Tree Regressor

Aqui é treinado um modelo de árvore de decisão para regressão.
Essa abordagem captura não linearidades e pode ser ajustada com `max_depth`.
Neste bloco é treinado um modelo de Decision Tree Regressor usando os dados de treino. Depois o modelo é validado com os dados de validação e por fim são somados os datasets de treinamento e validação, para criar um modelo final que será testado com os dados de teste.
Em seguida são calculadas métricas de desempenho para avaliar a qualidade do ajuste.

In [74]:
model_train_dt = tr.DecisionTreeRegressor(max_depth=12)
model_train_dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=12)

In [75]:
#Previsão sobre os dados de treinamento
y_pred_train_dt = model_train_dt.predict( X_train )

# # R²
r2_squared_train_dt = mt.r2_score(y_train, y_pred_train_dt)
print("R²:", r2_squared_train_dt)
# MSE 
mse_train_dt = mt.mean_squared_error(y_train, y_pred_train_dt)
print("MSE", mse_train_dt)
# RMSE
rmse_train_dt = np.sqrt(mse_train_dt)
print("RMSE", rmse_train_dt)
# MAE
mae_train_dt = mt.mean_absolute_error(y_train, y_pred_train_dt)
print("MAE", mae_train_dt)
# MAPE
y_train_flat_dt = y_train.values.ravel()
y_pred_train_dt = y_pred_train_dt.ravel()

mask = y_train_flat_dt != 0
mape_train_dt = np.mean(
    np.abs((y_train_flat_dt[mask] - y_pred_train_dt[mask]) / y_train_flat_dt[mask])
)
print("MAPE", mape_train_dt)

R²: 0.8980230897903089
MSE 0.02504190266125562
RMSE 0.15824633538017752
MAE 0.05008380532251125
MAPE 0.05778011873109813

In [18]:
#Verificando o melhor valor de max_depth para o Decision Tree Regressor
max_depth_values = range(1, 31)
resultados_dt = []
for i in range(1,31):
    model_val_dt = tr.DecisionTreeRegressor(max_depth=i)
    model_val_dt.fit(X_train, y_train)

    y_pred_val = model_val_dt.predict(X_val)
    
    # Cálculo das métricas
    r2 = mt.r2_score(y_val, y_pred_val)
    mse = mt.mean_squared_error(y_val, y_pred_val)
    rmse = np.sqrt(mse)
    mae = mt.mean_absolute_error(y_val, y_pred_val)
    mape = mt.mean_absolute_percentage_error(y_val, y_pred_val)
    
    # Salva os resultados em um dicionário
    resultados_dt.append({
        'max_depth': i,
        'R2': r2,
        'MSE': mse,
        'RMSE': rmse,
        'MAE': mae,
        'MAPE': mape
    })

# Transforma em DataFrame para facilitar a visualização
dt_resultados = pd.DataFrame(resultados_dt)

# Ordena pelo melhor R² ou menor RMSE
dt_resultados = dt_resultados.sort_values(by='R2', ascending=False)
print(dt_resultados)

    max_depth        R2       MSE      RMSE       MAE          MAPE
11         12  0.840985  0.039048  0.197606  0.064369  1.450785e+14
10         11  0.839206  0.039485  0.198708  0.068937  1.564427e+14
12         13  0.838539  0.039649  0.199119  0.061686  1.412666e+14
13         14  0.836351  0.040186  0.200464  0.059285  1.344082e+14
9          10  0.834421  0.040660  0.201643  0.074002  1.680186e+14
14         15  0.831227  0.041444  0.203578  0.057608  1.301202e+14
8           9  0.829712  0.041816  0.204490  0.079414  1.804475e+14
15         16  0.824503  0.043095  0.207594  0.056894  1.286643e+14
16         17  0.816823  0.044981  0.212088  0.056381  1.296338e+14
7           8  0.816328  0.045103  0.212374  0.087719  1.977591e+14
17         18  0.815196  0.045381  0.213028  0.054733  1.248376e+14
18         19  0.808020  0.047143  0.217124  0.054747  1.250735e+14
19         20  0.802246  0.048561  0.220365  0.054660  1.240091e+14
6           7  0.800707  0.048939  0.221221  0.096611  2.178493e+14
20         21  0.797837  0.049643  0.222808  0.054354  1.238907e+14
22         23  0.788441  0.051951  0.227927  0.054392  1.243850e+14
21         22  0.787854  0.052095  0.228243  0.055465  1.266559e+14
23         24  0.781657  0.053617  0.231553  0.055376  1.272465e+14
29         30  0.780099  0.053999  0.232377  0.054065  1.260190e+14
25         26  0.779887  0.054051  0.232489  0.054772  1.259330e+14
27         28  0.779796  0.054074  0.232537  0.054357  1.250847e+14
28         29  0.779750  0.054085  0.232562  0.054224  1.249058e+14
24         25  0.779607  0.054120  0.232637  0.055241  1.277491e+14
26         27  0.775926  0.055024  0.234572  0.055462  1.286331e+14
5           6  0.773326  0.055663  0.235929  0.110676  2.515697e+14
4           5  0.733173  0.065522  0.255974  0.130202  2.958759e+14
3           4  0.689707  0.076196  0.276036  0.152650  3.462498e+14
2           3  0.644296  0.087347  0.295546  0.176177  3.979204e+14
1           2  0.513391  0.119492  0.345677  0.238302  5.347008e+14
0           1  0.332435  0.163928  0.404881  0.326681  7.347553e+14

In [19]:
#Previsão sobre os dados de validação
y_pred_val_dt = model_train_dt.predict( X_val )
# # R²
r2_squared_val_dt = mt.r2_score(y_val, y_pred_val_dt)
print("R²:", r2_squared_val_dt)
# MSE 
mse_val_dt = mt.mean_squared_error(y_val, y_pred_val_dt)
print("MSE", mse_val_dt)
# RMSE
rmse_val_dt= np.sqrt(mse_val_dt)
print("RMSE", rmse_val_dt)
# MAE
mae_val_dt = mt.mean_absolute_error(y_val, y_pred_val_dt)
print("MAE", mae_val_dt)
# MAPE
y_val_flat_dt = y_val.values.ravel()
y_pred_val_dt = y_pred_val_dt.ravel()

mask = y_val_flat_dt != 0
mape_val_dt = np.mean(
    np.abs((y_val_flat_dt[mask] - y_pred_val_dt[mask]) / y_val_flat_dt[mask])
)
print("MAPE", mape_val_dt)

R²: 0.8426512400043792
MSE 0.038638829411651476
RMSE 0.1965676204557899
MAE 0.0639750296224571
MAPE 0.0730505170565423

In [20]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
model_last_dt = tr.DecisionTreeRegressor(max_depth=12)
model_last_dt.fit( np.concatenate( (X_train, X_val) ), np.concatenate((y_train, y_val)) )

DecisionTreeRegressor(max_depth=12)

In [21]:
# Model Performance da validação para comparação com os dados de teste
#Previsão sobre os dados de teste
y_pred_test_dt = model_last_dt.predict( X_test )
# # R²
r2_squared_test_dt = mt.r2_score(y_test, y_pred_test_dt)
print("R²:", r2_squared_test_dt)
# MSE 
mse_test_dt = mt.mean_squared_error(y_test, y_pred_test_dt)
print("MSE", mse_test_dt)
# RMSE
rmse_test_dt= np.sqrt(mse_test_dt)
print("RMSE", rmse_test_dt)
# MAE
mae_test_dt = mt.mean_absolute_error(y_test, y_pred_test_dt)
print("MAE", mae_test_dt)
# MAPE
y_test_flat_dt = y_test.values.ravel()
y_pred_test_dt = y_pred_test_dt.ravel()

mask = y_test_flat_dt != 0
mape_test_dt = np.mean(
    np.abs((y_test_flat_dt[mask] - y_pred_test_dt[mask]) / y_test_flat_dt[mask])
)
print("MAPE", mape_test_dt)

R²: 0.851853227781151
MSE 0.03648402311503185
RMSE 0.19100791374974976
MAE 0.06297984207594111
MAPE 0.07161423273102459

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but DecisionTreeRegressor was fitted without feature names
  warnings.warn(

## Random Forest Regressor

Neste bloco é treinado um modelo de Random Forest para regressão.
A ideia é combinar várias árvores para melhorar a estabilidade e reduzir overfitting.
Neste bloco é treinado um modelo de Random Forest Regressor usando os dados de treino. Depois o modelo é validado com os dados de validação e por fim são somados os datasets de treinamento e validação, para criar um modelo final que será testado com os dados de teste.
Em seguida são calculadas métricas de desempenho para avaliar a qualidade do ajuste.

In [22]:
#Instanciando e treinando a Random Forest Regressor
model_train_rf = RandomForestRegressor(n_estimators=100, max_depth=30)
model_train_rf.fit(X_train, y_train)

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(max_depth=30)

In [23]:
# Model Performance do treinamento para comparação com o teste
#Previsão sobre os dados de treinamento
y_pred_train_rf = model_train_rf.predict( X_train )
# # R²
r2_squared_train_rf = mt.r2_score(y_train, y_pred_train_rf)
print("R²:", r2_squared_train_rf)
# MSE 
mse_train_rf = mt.mean_squared_error(y_train, y_pred_train_rf)
print("MSE", mse_train_rf)
# RMSE
rmse_train_rf = np.sqrt(mse_train_rf)
print("RMSE", rmse_train_rf)
# MAE
mae_train_rf = mt.mean_absolute_error(y_train, y_pred_train_rf)
print("MAE", mae_train_rf)
# MAPE
y_train_flat_rf = y_train.values.ravel()
y_pred_train_rf = y_pred_train_rf.ravel()

mask = y_train_flat_rf != 0
mape_train_rf = np.mean(
    np.abs((y_train_flat_rf[mask] - y_pred_train_rf[mask]) / y_train_flat_rf[mask])
)
print("MAPE", mape_train_rf)

R²: 0.9838672146684735
MSE 0.003961638365942829
RMSE 0.06294154721599103
MAE 0.021823677886947116
MAPE 0.0243504004265634

In [24]:
#LOOP para investigar os melhores parâmetros do Random Forest Regressor
# Definição dos parâmetros para investigação
n_estimators_list = [50, 100, 200, 500]
max_depth_list = [5, 10, 20, 30]

resultados = []

for n in n_estimators_list:
    for d in max_depth_list:
        # Inicializa e treina o modelo
        model = RandomForestRegressor(n_estimators=n, max_depth=d, random_state=42, n_jobs=-1)
        model.fit(X_train, y_train)
        
        # Predições
        y_pred = model.predict(X_val)
        
        # Cálculo das métricas
        r2 = mt.r2_score(y_val, y_pred)
        mse = mt.mean_squared_error(y_val, y_pred)
        rmse = np.sqrt(mse)
        mae = mt.mean_absolute_error(y_val, y_pred)
        mape = mt.mean_absolute_percentage_error(y_val, y_pred)
        
        # Salva os resultados em um dicionário
        resultados.append({
            'n_estimators': n,
            'max_depth': d,
            'R2': r2,
            'MSE': mse,
            'RMSE': rmse,
            'MAE': mae,
            'MAPE': mape
        })

# Transforma em DataFrame para facilitar a visualização
df_resultados = pd.DataFrame(resultados)

# Ordena pelo melhor R² ou menor RMSE
df_resultados = df_resultados.sort_values(by='R2', ascending=False)
print(df_resultados)

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

    n_estimators  max_depth        R2       MSE      RMSE       MAE  \
15           500         30  0.886683  0.027826  0.166813  0.059671
11           200         30  0.886339  0.027911  0.167065  0.059619
14           500         20  0.886173  0.027952  0.167187  0.059705
7            100         30  0.885906  0.028017  0.167383  0.059525
10           200         20  0.885727  0.028061  0.167515  0.059697
6            100         20  0.885646  0.028081  0.167574  0.059501
3             50         30  0.884757  0.028299  0.168224  0.059369
2             50         20  0.884485  0.028366  0.168422  0.059433
13           500         10  0.857487  0.034996  0.187072  0.075499
9            200         10  0.857145  0.035080  0.187296  0.075588
5            100         10  0.856732  0.035181  0.187566  0.075664
1             50         10  0.856560  0.035223  0.187679  0.075558
12           500          5  0.734398  0.065222  0.255385  0.130548
8            200          5  0.734367  0.065229  0.255400  0.130639
4            100          5  0.734094  0.065296  0.255531  0.130600
0             50          5  0.733901  0.065344  0.255624  0.130465

            MAPE
15  1.399914e+14
11  1.396647e+14
14  1.389472e+14
7   1.395390e+14
10  1.388166e+14
6   1.384191e+14
3   1.387939e+14
2   1.379398e+14
13  1.708805e+14
9   1.710625e+14
5   1.713166e+14
1   1.710067e+14
12  2.966506e+14
8   2.969207e+14
4   2.968622e+14
0   2.963006e+14

In [25]:
# Model Performance do treinamento para comparação com o teste
#Previsão sobre os dados de validação
y_pred_val_rf = model_train_rf.predict( X_val )
# # R²
r2_squared_val_rf = mt.r2_score(y_val, y_pred_val_rf)
print("R²:", r2_squared_val_rf)
# MSE 
mse_val_rf = mt.mean_squared_error(y_val, y_pred_val_rf)
print("MSE", mse_val_rf)
# RMSE
rmse_val_rf = np.sqrt(mse_val_rf)
print("RMSE", rmse_val_rf)
# MAE
mae_val_rf = mt.mean_absolute_error(y_val, y_pred_val_rf)
print("MAE", mae_val_rf)
# MAPE
y_val_flat_rf = y_val.values.ravel()
y_pred_val_rf = y_pred_val_rf.ravel()

mask = y_val_flat_rf != 0
mape_val_rf = np.mean(
    np.abs((y_val_flat_rf[mask] - y_pred_val_rf[mask]) / y_val_flat_rf[mask])
)
print("MAPE", mape_val_rf)

R²: 0.885083163482849
MSE 0.02821917403630264
RMSE 0.1679856363987786
MAE 0.05985041125152091
MAPE 0.0660675721297023

In [26]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
model_last_rf = RandomForestRegressor(n_estimators=100, max_depth=20)
model_last_rf.fit( np.concatenate( (X_train, X_val) ), np.concatenate((y_train, y_val)) )

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(max_depth=20)

In [27]:
# Model Performance validada com os dados de teste e treinada com os dados de treinamento e validação juntos
#Previsão sobre os dados de teste
y_pred_test_rf = model_last_rf.predict( X_test )
# # R²
r2_squared_test_rf = mt.r2_score(y_test, y_pred_test_rf)
print("R²:", r2_squared_test_rf)
# MSE 
mse_test_rf = mt.mean_squared_error(y_test, y_pred_test_rf)
print("MSE", mse_test_rf)
# RMSE
rmse_test_rf = np.sqrt(mse_test_rf)
print("RMSE", rmse_test_rf)
# MAE
mae_test_rf = mt.mean_absolute_error(y_test, y_pred_test_rf)
print("MAE", mae_test_rf)
# MAPE
y_test_flat_rf = y_test.values.ravel()
y_pred_test_rf = y_pred_test_rf.ravel()

mask = y_test_flat_rf != 0
mape_test_rf = np.mean(
    np.abs((y_test_flat_rf[mask] - y_pred_test_rf[mask]) / y_test_flat_rf[mask])
)
print("MAPE", mape_test_rf)

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(

R²: 0.8885104922062973
MSE 0.027456459013633822
RMSE 0.16569990649856692
MAE 0.05640069565475936
MAPE 0.06205887678474431

## Polinomial Regression

Aqui é aplicado um modelo de regressão polinomial para capturar relações não lineares entre as variáveis.
Os dados de entrada são transformados em termos polinomiais antes do ajuste, é treinado com um modelo de  regressão linear simples usando os dados de treino. Depois o modelo é validado com os dados de validação e por fim são somados os datasets de treinamento e validação, para criar um modelo final que será testado com os dados de teste.
Em seguida são calculadas métricas de desempenho para avaliar a qualidade do ajuste.

In [28]:
# Polinomio
poly = pp.PolynomialFeatures(degree=3, include_bias=False)
X_poly = poly.fit_transform(X_train.values)

# model training
model_train_pr = LinearRegression()
model_train_pr.fit( X_poly, y_train )

LinearRegression()

In [29]:
#Previsão sobre os dados de treinamento
y_pred_train_pr = model_train_pr.predict( X_poly )
# # R²
r2_squared_train_pr = mt.r2_score(y_train, y_pred_train_pr)
print("R²:", r2_squared_train_pr)
# MSE 
mse_train_pr = mt.mean_squared_error(y_train, y_pred_train_pr)
print("MSE", mse_train_pr)
# RMSE
rmse_train_pr = np.sqrt(mse_train_pr)
print("RMSE", rmse_train_pr)
# MAE
mae_train_pr = mt.mean_absolute_error(y_train, y_pred_train_pr)
print("MAE", mae_train_pr)
# MAPE
y_train_flat_pr = y_train.values.ravel()
y_pred_train_pr = y_pred_train_pr.ravel()

mask = y_train_flat_pr != 0
mape_train_pr = np.mean(
    np.abs((y_train_flat_pr[mask] - y_pred_train_pr[mask]) / y_train_flat_pr[mask])
)
print("MAPE", mape_train_pr)

R²: 0.5436441218518615
MSE 0.1120647748198933
RMSE 0.33476077252254827
MAE 0.26692312467918855
MAPE 0.3155474949554338

In [30]:
#Previsão sobre os dados de validação
y_pred_val_pr = model_train_pr.predict(poly.transform(X_val.values))
# # R²
r2_squared_val_pr = mt.r2_score(y_val, y_pred_val_pr)
print("R²:", r2_squared_val_pr)
# MSE 
mse_val_pr = mt.mean_squared_error(y_val, y_pred_val_pr)
print("MSE", mse_val_pr)
# RMSE
rmse_val_pr = np.sqrt(mse_val_pr)
print("RMSE", rmse_val_pr)
# MAE
mae_val_pr = mt.mean_absolute_error(y_val, y_pred_val_pr)
print("MAE", mae_val_pr)
# MAPE
y_val_flat_pr = y_val.values.ravel()
y_pred_val_pr = y_pred_val_pr.ravel()

mask = y_val_flat_pr != 0
mape_val_pr = np.mean(
    np.abs((y_val_flat_pr[mask] - y_pred_val_pr[mask]) / y_val_flat_pr[mask])
)
print("MAPE", mape_val_pr)

R²: 0.5425782424389733
MSE 0.11232526560787773
RMSE 0.3351496167503071
MAE 0.26672526635120486
MAPE 0.315294627864998

In [31]:
X_all = np.concatenate((X_train, X_val), axis=0)
y_all = np.concatenate((y_train.values, y_val.values), axis=0)

# Polinomio teste
poly = pp.PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X_all)

model_last_pr = LinearRegression()
model_last_pr.fit(X_poly, y_all)

LinearRegression()

In [32]:
# Model Performance do treinamento para comparação com o teste
#Previsão sobre os dados de validação
y_pred_test_pr = model_last_pr.predict(poly.transform(X_test.values))
# # R²
r2_squared_test_pr = mt.r2_score(y_test, y_pred_test_pr)
print("R²:", r2_squared_test_pr)
# MSE 
mse_test_pr = mt.mean_squared_error(y_test, y_pred_test_pr)
print("MSE", mse_test_pr)
# RMSE
rmse_test_pr = np.sqrt(mse_test_pr)
print("RMSE", rmse_test_pr)
# MAE
mae_test_pr = mt.mean_absolute_error(y_test, y_pred_test_pr)
print("MAE", mae_test_pr)
# MAPE
y_test_flat_pr = y_test.values.ravel()
y_pred_test_pr = y_pred_test_pr.ravel()

mask = y_test_flat_pr != 0
mape_test_pr = np.mean(
    np.abs((y_test_flat_pr[mask] - y_pred_test_pr[mask]) / y_test_flat_pr[mask])
)
print("MAPE", mape_test_pr)

R²: 0.6558958483670156
MSE 0.08474233784594683
RMSE 0.29110537240996914
MAE 0.20970106357744345
MAPE 0.2445982099032214

## Lasso L1 - Linear Regression

Esta seção implementa um algorítimo de reularização Lasso, para melhorar a performace do modelo de regressão linear

In [ ]:
model_lasso_lr = lm.Lasso(alpha=0.009, max_iter=1000)
model_lasso_lr.fit(X_train, y_train)

Lasso(alpha=0.009)

In [34]:
#Previsão sobre os dados de treinamento
y_pred_lasso_train = model_lasso_lr.predict( X_train )
# # R²
r2_squared_train_la = mt.r2_score(y_train, y_pred_lasso_train)
print("R²:", r2_squared_train_la)
# MSE 
mse_train_la = mt.mean_squared_error(y_train, y_pred_lasso_train)
print("MSE", mse_train)
# RMSE
rmse_train_la = np.sqrt(mse_train)
print("RMSE", rmse_train)
# MAE
mae_train_la = mt.mean_absolute_error(y_train, y_pred_lasso_train)
print("MAE", mae_train)
# MAPE
y_train_flat_la = y_train.values.ravel()
y_pred_lasso_train_flat = y_pred_lasso_train.ravel()

mask = y_train_flat != 0
mape_train_la = np.mean(
    np.abs((y_train_flat[mask] - y_pred_lasso_train_flat[mask]) / y_train_flat[mask])
)
print("MAPE", mape_train_la)

R²: 0.5231018098943119
MSE 0.1096323327773033
RMSE 0.3311077359067639
MAE 0.24902069470379487
MAPE 0.3061908441809131

In [ ]:
#Previsão sobre os dados de validação
y_pred_lasso_val = model_lasso_lr.predict( X_val )
# # R²
r2_squared_val_la = mt.r2_score(y_val, y_pred_lasso_val)
print("R²:", r2_squared_val_la)
# MSE 
mse_val_la = mt.mean_squared_error(y_val, y_pred_lasso_val)
print("MSE", mse_val_la)
# RMSE
rmse_val_la = np.sqrt(mse_val_la)
print("RMSE", rmse_val_la)
# MAE
mae_val_la = mt.mean_absolute_error(y_val, y_pred_lasso_val)
print("MAE", mae_val_la)
# MAPE
y_val_flat_la = y_val.values.ravel()
y_pred_lasso_val_flat_la = y_pred_lasso_val.ravel()

mask = y_val_flat_la != 0
mape_val_la = np.mean(
    np.abs((y_val_flat_la[mask] - y_pred_lasso_val_flat_la[mask]) / y_val_flat_la[mask])
)
print("MAPE", mape_val_la)

R²: 0.5188651506312836
MSE 0.11814829280685697
RMSE 0.34372706149917404
MAE 0.27656069723576626
MAPE 0.3079822424599463

In [36]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
model_last_lasso_lr = lm.Lasso(alpha=0.009, max_iter=1000)
model_last_lasso_lr.fit( np.concatenate( (X_train, X_val) ), np.concatenate((y_train, y_val)) )

Lasso(alpha=0.009)

In [37]:
#Previsão sobre os dados de treinamento
y_pred_lasso_teste = model_last_lasso_lr.predict( X_test )
# # R²
r2_squared_test_la = mt.r2_score(y_test, y_pred_lasso_teste)
print("R²:", r2_squared_test_la)
# MSE 
mse_test_la = mt.mean_squared_error(y_test, y_pred_lasso_teste)
print("MSE", mse_test_la)
# RMSE
rmse_test_la = np.sqrt(mse_test_la)
print("RMSE", rmse_test_la)
# MAE
mae_test_la = mt.mean_absolute_error(y_test, y_pred_lasso_teste)
print("MAE", mae_test_la)
# MAPE
y_test_flat = y_test.values.ravel()
y_pred_lasso_teste_flat = y_pred_lasso_teste.ravel()

mask = y_test_flat != 0
mape_test_la = np.mean(
    np.abs((y_test_flat[mask] - y_pred_lasso_teste_flat[mask]) / y_test_flat[mask])
)
print("MAPE", mape_test_la)

R²: 0.5147167999202575
MSE 0.11951042350683969
RMSE 0.34570279649843694
MAE 0.2783783483478729
MAPE 0.30866765585927564

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but Lasso was fitted without feature names
  warnings.warn(

## Ridge L2 - Linear Regression

Esta seção implementa um algorítimo de reularização Ridge, para melhorar a performace do modelo de regressão linear

In [38]:
model_ridge_lr = lm.Ridge(alpha=0.012, max_iter=1000)
model_ridge_lr.fit(X_train, y_train)

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.177750914073071e-16.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

Ridge(alpha=0.012, max_iter=1000)

In [39]:
#Previsão sobre os dados de treinamento
y_pred_ridge_train = model_ridge_lr.predict( X_train )
# # R²
r2_squared_train_ri = mt.r2_score(y_train, y_pred_ridge_train)
print("R²:", r2_squared_train_ri)
# MSE 
mse_train_ri = mt.mean_squared_error(y_train, y_pred_ridge_train)
print("MSE", mse_train_ri)
# RMSE
rmse_train_ri = np.sqrt(mse_train_ri)
print("RMSE", rmse_train_ri)
# MAE
mae_train_ri = mt.mean_absolute_error(y_train, y_pred_ridge_train)
print("MAE", mae_train_ri)
# MAPE
y_train_flat_ri = y_train.values.ravel()
y_pred_ridge_train_flat_ri = y_pred_ridge_train.ravel()

mask = y_train_flat_ri != 0
mape_train_ri = np.mean(
    np.abs((y_train_flat_ri[mask] - y_pred_ridge_train_flat_ri[mask]) / y_train_flat_ri[mask])
)
print("MAPE", mape_train_ri)

R²: 0.553549631991898
MSE 0.10963233378763597
RMSE 0.3311077374324496
MAE 0.2490206108436681
MAPE 0.26678257237586855

In [40]:
#Previsão sobre os dados de treinamento
y_pred_ridge_val = model_ridge_lr.predict( X_val )
# # R²
r2_squared_val_ri = mt.r2_score(y_val, y_pred_ridge_val)
print("R²:", r2_squared_val_ri)
# MSE 
mse_val_ri = mt.mean_squared_error(y_val, y_pred_ridge_val)
print("MSE", mse_val_ri)
# RMSE
rmse_val_ri = np.sqrt(mse_val_ri)
print("RMSE", rmse_val_ri)
# MAE
mae_val_ri = mt.mean_absolute_error(y_val, y_pred_ridge_val)
print("MAE", mae_val_ri)
# MAPE
y_val_flat = y_val.values.ravel()
y_pred_ridge_val_flat = y_pred_ridge_val.ravel()

mask = y_val_flat != 0
mape_val_ri = np.mean(
    np.abs((y_val_flat[mask] - y_pred_ridge_val_flat[mask]) / y_val_flat[mask])
)
print("MAPE", mape_val_ri)

R²: 0.5477791422471181
MSE 0.11104812379576817
RMSE 0.3332388389665409
MAE 0.24996841998918987
MAPE 0.26953185372188915

In [41]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
model_last_ridge_lr = lm.Ridge(alpha=0.01, max_iter=1000)
model_last_ridge_lr.fit( np.concatenate( (X_train, X_val) ), np.concatenate((y_train, y_val)) )

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 6.878788119788414e-17.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

Ridge(alpha=0.01, max_iter=1000)

In [42]:
#Previsão sobre os dados de treinamento
y_pred_ridge_teste = model_last_ridge_lr.predict( X_test )
# # R²
r2_squared_test_ri = mt.r2_score(y_test, y_pred_ridge_teste)
print("R²:", r2_squared_test_ri)
# MSE 
mse_test_ri = mt.mean_squared_error(y_test, y_pred_ridge_teste)
print("MSE", mse_test_ri)
# RMSE
rmse_test_ri = np.sqrt(mse_test_ri)
print("RMSE", rmse_test_ri)
# MAE
mae_test_ri = mt.mean_absolute_error(y_test, y_pred_ridge_teste)
print("MAE", mae_test_ri)
# MAPE
y_test_flat = y_test.values.ravel()
y_pred_ridge_teste_flat = y_pred_ridge_teste.ravel()

mask = y_test_flat != 0
mape_test_ri = np.mean(
    np.abs((y_test_flat[mask] - y_pred_ridge_teste_flat[mask]) / y_test_flat[mask])
)
print("MAPE", mape_test_ri)

R²: 0.549519707603698
MSE 0.11093953080782612
RMSE 0.3330758634422887
MAE 0.2499694882929012
MAPE 0.2683684170810425

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but Ridge was fitted without feature names
  warnings.warn(

## ElasticNet - Linear Regression

Esta seção implementa um algorítimo de reularização ElasticNet, para melhorar a performace do modelo de regressão linear

In [43]:
model_net_lr = lm.ElasticNet(alpha=0.001, l1_ratio=0.05, max_iter=2000)
model_net_lr.fit(X_train, y_train)

ElasticNet(alpha=0.001, l1_ratio=0.05, max_iter=2000)

In [44]:
#Previsão sobre os dados de treinamento
y_pred_net_train = model_net_lr.predict( X_train )
# # R²
r2_squared_train_ne = mt.r2_score(y_train, y_pred_net_train)
print("R²:", r2_squared_train_ne)
# MSE 
mse_train_ne = mt.mean_squared_error(y_train, y_pred_net_train)
print("MSE", mse_train_ne)
# RMSE
rmse_train_ne = np.sqrt(mse_train_ne)
print("RMSE", rmse_train_ne)
# MAE
mae_train_ne = mt.mean_absolute_error(y_train, y_pred_net_train)
print("MAE", mae_train_ne)
# MAPE
y_train_flat_ne = y_train.values.ravel()
y_pred_net_train_flat_ne = y_pred_net_train.ravel()

mask = y_train_flat_ne != 0
mape_train_ne = np.mean(
    np.abs((y_train_flat_ne[mask] - y_pred_net_train_flat_ne[mask]) / y_train_flat_ne[mask])
)
print("MAPE", mape_train_ne)

R²: 0.5530226059341359
MSE 0.10976175264540765
RMSE 0.33130311294252524
MAE 0.24960449886465022
MAPE 0.26758486975216156

In [45]:
#Previsão sobre os dados de treinamento
y_pred_net_val = model_net_lr.predict( X_val )
# # R²
r2_squared_val_ne = mt.r2_score(y_val, y_pred_net_val)
print("R²:", r2_squared_val_ne)
# MSE 
mse_val_ne = mt.mean_squared_error(y_val, y_pred_net_val)
print("MSE", mse_val_ne)
# RMSE
rmse_val_ne = np.sqrt(mse_val_ne)
print("RMSE", rmse_val_ne)
# MAE
mae_val_ne = mt.mean_absolute_error(y_val, y_pred_net_val)
print("MAE", mae_val_ne)
# MAPE
y_val_flat = y_val.values.ravel()
y_pred_net_val_flat = y_pred_net_val.ravel()

mask = y_val_flat != 0
mape_val_ne = np.mean(
    np.abs((y_val_flat[mask] - y_pred_net_val_flat[mask]) / y_val_flat[mask])
)
print("MAPE", mape_val_ne)

R²: 0.5473451661934232
MSE 0.11115469169441529
RMSE 0.3333986977995194
MAE 0.2505706383952901
MAPE 0.2702733917062782

In [46]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
model_last_net_lr = lm.ElasticNet(alpha=0.001, l1_ratio=0.05, max_iter=2000)
model_last_net_lr.fit( np.concatenate( (X_train, X_val) ), np.concatenate((y_train, y_val)) )

ElasticNet(alpha=0.001, l1_ratio=0.05, max_iter=2000)

In [47]:
#Previsão sobre os dados de treinamento
y_pred_net_teste = model_last_net_lr.predict( X_test )
# # R²
r2_squared_test_ne = mt.r2_score(y_test, y_pred_net_teste)
print("R²:", r2_squared_test_ne)
# MSE 
mse_test_ne = mt.mean_squared_error(y_test, y_pred_net_teste)
print("MSE", mse_test_ne)
# RMSE
rmse_test_ne = np.sqrt(mse_test_ne)
print("RMSE", rmse_test_ne)
# MAE
mae_test_ne = mt.mean_absolute_error(y_test, y_pred_net_teste)
print("MAE", mae_test_ne)
# MAPE
y_test_flat = y_test.values.ravel()
y_pred_net_teste_flat = y_pred_net_teste.ravel()

mask = y_test_flat != 0
mape_test_ne = np.mean(
    np.abs((y_test_flat[mask] - y_pred_net_teste_flat[mask]) / y_test_flat[mask])
)
print("MAPE", mape_test_ne)

R²: 0.5488934357185853
MSE 0.11109376243630192
RMSE 0.3333073093052445
MAE 0.2506093467305722
MAPE 0.26914966596365375

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but ElasticNet was fitted without feature names
  warnings.warn(

## Lasso L1 - Polynomial Regression

Esta seção implementa um algorítimo de reularização Lasso, para melhorar a performace do modelo de regressão Polinomial

Aqui é aplicado um modelo de regressão polinomial para capturar relações não lineares entre as variáveis.
Os dados de entrada são transformados em termos polinomiais antes do ajuste.

In [48]:
# Polinomio
poly = pp.PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X_train.values)

In [49]:
## Lasso L1 - Linear Regression
model_lasso_pr = lm.Lasso(alpha=0.001, max_iter=3000)
model_lasso_pr.fit(X_poly, y_train)

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.984e+03, tolerance: 1.781e+00
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=0.001, max_iter=3000)

In [50]:
#Previsão sobre os dados de treinamento
y_pred_lasso_pr_train = model_lasso_pr.predict(poly.transform(X_train.values))
# # R²
r2_squared_train_la_pr = mt.r2_score(y_train, y_pred_lasso_pr_train)
print("R²:", r2_squared_train_la_pr)
# MSE 
mse_train_la_pr = mt.mean_squared_error(y_train, y_pred_lasso_pr_train)
print("MSE", mse_train_la_pr)
# RMSE
rmse_train_la_pr = np.sqrt(mse_train_la_pr)
print("RMSE", rmse_train_la_pr)
# MAE
mae_train_la_pr = mt.mean_absolute_error(y_train, y_pred_lasso_pr_train)
print("MAE", mae_train_la_pr)
# MAPE
y_train_flat_la_pr = y_train.values.ravel()
y_pred_lasso_pr_train_flat = y_pred_lasso_pr_train.ravel()

mask = y_train_flat_la_pr != 0
mape_train_la_pr = np.mean(
    np.abs((y_train_flat_la_pr[mask] - y_pred_lasso_pr_train_flat[mask]) / y_train_flat_la_pr[mask])
)
print("MAPE", mape_train_la_pr)

R²: 0.7175117900894981
MSE 0.0693690585543831
RMSE 0.26338006483859616
MAE 0.1904951701964183
MAPE 0.23352102010590609

In [ ]:
#Previsão sobre os dados de validação
y_pred_lasso_pr_val = model_lasso_pr.predict(poly.transform(X_val.values))
# # R²
r2_squared_val_la_pr = mt.r2_score(y_val, y_pred_lasso_pr_val)
print("R²:", r2_squared_val_la_pr)
# MSE 
mse_val_la_pr = mt.mean_squared_error(y_val, y_pred_lasso_pr_val)
print("MSE", mse_val_la_pr)
# RMSE
rmse_val_la_pr = np.sqrt(mse_val_la_pr)
print("RMSE", rmse_val_la_pr)
# MAE
mae_val_la_pr = mt.mean_absolute_error(y_val, y_pred_lasso_pr_val)
print("MAE", mae_val_la_pr)
# MAPE
y_val_flat_la_pr = y_val.values.ravel()
y_pred_lasso_pr_val_flat_la_pr = y_pred_lasso_pr_val.ravel()

mask = y_val_flat_la_pr != 0
mape_val_la_pr = np.mean(
    np.abs((y_val_flat_la_pr[mask] - y_pred_lasso_pr_val_flat_la_pr[mask]) / y_val_flat_la_pr[mask])
)
print("MAPE", mape_val_la_pr)

R²: 0.7155429188711555
MSE 0.069851765167896
RMSE 0.2642948451406043
MAE 0.1912160264387665
MAPE 0.23451655162975024

In [ ]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
X_all_pr = np.concatenate((X_train, X_val), axis=0)
y_all_pr = np.concatenate((y_train.values, y_val.values), axis=0)

# Polinomio teste
poly = pp.PolynomialFeatures(degree=2, include_bias=False)
X_poly_pr = poly.fit_transform(X_all_pr)

model_last_lasso_pr = lm.Lasso(alpha=0.001, max_iter=3000)
model_last_lasso_pr.fit(X_poly_pr, y_all_pr)

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.270e+03, tolerance: 2.544e+00
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=0.001, max_iter=3000)

In [ ]:
#Previsão sobre os dados de teste
y_pred_lasso_pr_teste = model_last_lasso_pr.predict( poly.transform(X_test.values))
# # R²
r2_squared_test_la_pr = mt.r2_score(y_test, y_pred_lasso_pr_teste)
print("R²:", r2_squared_test_la_pr)
# MSE 
mse_test_la_pr = mt.mean_squared_error(y_test, y_pred_lasso_pr_teste)
print("MSE", mse_test_la_pr)
# RMSE
rmse_test_la_pr = np.sqrt(mse_test_la_pr)
print("RMSE", rmse_test_la_pr)
# MAE
mae_test_la_pr = mt.mean_absolute_error(y_test, y_pred_lasso_pr_teste)
print("MAE", mae_test_la_pr)
# MAPE
y_test_flat_la_pr = y_test.values.ravel()
y_pred_lasso_pr_teste_flat_la_pr = y_pred_lasso_pr_teste.ravel()

mask = y_test_flat_la_pr != 0
mape_test_la_pr = np.mean(
    np.abs((y_test_flat_la_pr[mask] - y_pred_lasso_pr_teste_flat_la_pr[mask]) / y_test_flat_la_pr[mask])
)
print("MAPE", mape_test_la_pr)

R²: 0.7167125040195894
MSE 0.06976505391748114
RMSE 0.2641307515558935
MAE 0.19128031694319877
MAPE 0.23316430479614544

## Ridge L2 - Polynomial Regression

Esta seção implementa um algorítimo de reularização Ridge, para melhorar a performace do modelo de regressão Polinomial

Aqui é aplicado um modelo de regressão polinomial para capturar relações não lineares entre as variáveis.
Os dados de entrada são transformados em termos polinomiais antes do ajuste.

In [54]:
## Ridge L2 - Polynomial Regression
# Polinomio
poly = pp.PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X_train.values)

In [55]:
## Ridge L2 - Linear Regression
model_ridge_pr = lm.Ridge(alpha=0.001, max_iter=3000)
model_ridge_pr.fit(X_poly, y_train)

Ridge(alpha=0.001, max_iter=3000)

In [56]:
#Previsão sobre os dados de treinamento
y_pred_ridge_pr_train = model_ridge_pr.predict(poly.transform(X_train.values))
# # R²
r2_squared_train_ri_pr = mt.r2_score(y_train, y_pred_ridge_pr_train)
print("R²:", r2_squared_train_ri_pr)
# MSE 
mse_train_ri_pr = mt.mean_squared_error(y_train, y_pred_ridge_pr_train)
print("MSE", mse_train_ri_pr)
# RMSE
rmse_train_ri_pr = np.sqrt(mse_train_ri_pr)
print("RMSE", rmse_train_ri_pr)
# MAE
mae_train_ri_pr = mt.mean_absolute_error(y_train, y_pred_ridge_pr_train)
print("MAE", mae_train_ri_pr)
# MAPE
y_train_flat_ri_pr = y_train.values.ravel()
y_pred_ridge_pr_train_flat = y_pred_ridge_pr_train.ravel()

mask = y_train_flat_ri_pr != 0
mape_train_ri_pr = np.mean(
    np.abs((y_train_flat_ri_pr[mask] - y_pred_ridge_pr_train_flat[mask]) / y_train_flat_ri_pr[mask])
)
print("MAPE", mape_train_ri_pr)

R²: 0.7510316465891991
MSE 0.06113777382572502
RMSE 0.24726053835119954
MAE 0.17781435598069445
MAPE 0.20940627905671744

In [ ]:
#Previsão sobre os dados de validação
y_pred_ridge_pr_val = model_ridge_pr.predict(poly.transform(X_val.values))
# # R²
r2_squared_val_ri_pr = mt.r2_score(y_val, y_pred_ridge_pr_val)
print("R²:", r2_squared_val_ri_pr)
# MSE 
mse_val_ri_pr = mt.mean_squared_error(y_val, y_pred_ridge_pr_val)
print("MSE", mse_val_ri_pr)
# RMSE
rmse_val_ri_pr = np.sqrt(mse_val_ri_pr)
print("RMSE", rmse_val_ri_pr)
# MAE
mae_val_ri_pr = mt.mean_absolute_error(y_val, y_pred_ridge_pr_val)
print("MAE", mae_val_ri_pr)
# MAPE
y_val_flat_ri_pr = y_val.values.ravel()
y_pred_ridge_pr_val_flat_ri_pr = y_pred_ridge_pr_val.ravel()

mask = y_val_flat_ri_pr != 0
mape_val_ri_pr = np.mean(
    np.abs((y_val_flat_ri_pr[mask] - y_pred_ridge_pr_val_flat_ri_pr[mask]) / y_val_flat_ri_pr[mask])
)
print("MAPE", mape_val_ri_pr)

R²: 0.7476924949674856
MSE 0.06195706052276514
RMSE 0.2489117524802016
MAE 0.17898338074835204
MAPE 0.21047072621391127

In [ ]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
X_all_pr = np.concatenate((X_train, X_val), axis=0)
y_all_pr = np.concatenate((y_train.values, y_val.values), axis=0)

# Polinomio teste
poly = pp.PolynomialFeatures(degree=2, include_bias=False)
X_poly_pr = poly.fit_transform(X_all_pr)

model_last_ridge_pr = lm.Ridge(alpha=0.001, max_iter=3000)
model_last_ridge_pr.fit(X_poly_pr, y_all_pr)

Ridge(alpha=0.001, max_iter=3000)

In [59]:
#Previsão sobre os dados de teste
y_pred_ridge_pr_teste = model_last_ridge_pr.predict( poly.transform(X_test.values))
# # R²
r2_squared_test_ri_pr = mt.r2_score(y_test, y_pred_ridge_pr_teste)
print("R²:", r2_squared_test_ri_pr)
# MSE 
mse_test_ri_pr = mt.mean_squared_error(y_test, y_pred_ridge_pr_teste)
print("MSE", mse_test_ri_pr)
# RMSE
rmse_test_ri_pr = np.sqrt(mse_test_ri_pr)
print("RMSE", rmse_test_ri_pr)
# MAE
mae_test_ri_pr = mt.mean_absolute_error(y_test, y_pred_ridge_pr_teste)
print("MAE", mae_test_ri_pr)
# MAPE
y_test_flat_ri_pr = y_test.values.ravel()
y_pred_ridge_pr_teste_flat_ri_pr = y_pred_ridge_pr_teste.ravel()

mask = y_test_flat_ri_pr != 0
mape_test_ri_pr = np.mean(
    np.abs((y_test_flat_ri_pr[mask] - y_pred_ridge_pr_teste_flat_ri_pr[mask]) / y_test_flat_ri_pr[mask])
)
print("MAPE", mape_test_ri_pr)

R²: 0.7487933451150234
MSE 0.06186452304161126
RMSE 0.2487257989063685
MAE 0.1787818525078811
MAPE 0.2096255582360716

## ElasticNet - Polynomial Regression

Esta seção implementa um algorítimo de reularização ElasticNet, para melhorar a performace do modelo de regressão Polinomial

Aqui é aplicado um modelo de regressão polinomial para capturar relações não lineares entre as variáveis.
Os dados de entrada são transformados em termos polinomiais antes do ajuste.

In [60]:
## Elastic Net - Polynomial Regression
# Polinomio
poly = pp.PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X_train.values)

In [61]:
## ElasticNet - Polynomial Regression
model_net_pr = lm.ElasticNet(alpha=0.001, l1_ratio=0.05, max_iter=2000)
model_net_pr.fit(X_poly, y_train)

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.487e+03, tolerance: 1.781e+00
  model = cd_fast.enet_coordinate_descent(

ElasticNet(alpha=0.001, l1_ratio=0.05, max_iter=2000)

In [62]:
#Previsão sobre os dados de treinamento
y_pred_net_pr_train = model_net_pr.predict( poly.transform(X_train.values))
# # R²
r2_squared_train_net_pr = mt.r2_score(y_train, y_pred_net_pr_train)
print("R²:", r2_squared_train_net_pr)
# MSE 
mse_train_net_pr = mt.mean_squared_error(y_train, y_pred_net_pr_train)
print("MSE", mse_train_net_pr)
# RMSE
rmse_train_net_pr = np.sqrt(mse_train_net_pr)
print("RMSE", rmse_train_net_pr)
# MAE
mae_train_net_pr = mt.mean_absolute_error(y_train, y_pred_net_pr_train)
print("MAE", mae_train_net_pr)
# MAPE
y_train_flat_net_pr = y_train.values.ravel()
y_pred_net_pr_train_flat_net_pr = y_pred_net_pr_train.ravel()

mask = y_train_flat_net_pr != 0
mape_train_net_pr = np.mean(
    np.abs((y_train_flat_net_pr[mask] - y_pred_net_pr_train_flat_net_pr[mask]) / y_train_flat_net_pr[mask])
)
print("MAPE", mape_train_net_pr)

R²: 0.7407446068407787
MSE 0.06366390496190774
RMSE 0.2523170722759515
MAE 0.18013611534280882
MAPE 0.21613395671375632

In [ ]:
#Previsão sobre os dados de validação
y_pred_net_pr_val = model_net_pr.predict( poly.transform(X_val.values))
# # R²
r2_squared_val_net_pr = mt.r2_score(y_val, y_pred_net_pr_val)
print("R²:", r2_squared_val_net_pr)
# MSE 
mse_val_net_pr = mt.mean_squared_error(y_val, y_pred_net_pr_val)
print("MSE", mse_val_net_pr)
# RMSE
rmse_val_net_pr = np.sqrt(mse_val_net_pr)
print("RMSE", rmse_val_net_pr)
# MAE
mae_val_net_pr = mt.mean_absolute_error(y_val, y_pred_net_pr_val)
print("MAE", mae_val_net_pr)
# MAPE
y_val_flat = y_val.values.ravel()
y_pred_net_pr_val_flat = y_pred_net_pr_val.ravel()

mask = y_val_flat != 0
mape_val_net_pr = np.mean(
    np.abs((y_val_flat[mask] - y_pred_net_pr_val_flat[mask]) / y_val_flat[mask])
)
print("MAPE", mape_val_net_pr)

R²: 0.7390048223202293
MSE 0.06409042020993996
RMSE 0.2531608583686269
MAE 0.18073223712765696
MAPE 0.2165489564301795

In [64]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
X_all_pr = np.concatenate((X_train, X_val), axis=0)
y_all_pr = np.concatenate((y_train.values, y_val.values), axis=0)

# Polinomio teste
poly = pp.PolynomialFeatures(degree=2, include_bias=False)
X_poly_pr = poly.fit_transform(X_all_pr)

model_last_net_pr = lm.Ridge(alpha=0.001, max_iter=3000)
model_last_net_pr.fit(X_poly_pr, y_all_pr)

Ridge(alpha=0.001, max_iter=3000)

In [ ]:
#Previsão sobre os dados de teste
y_pred_net_pr_teste = model_last_net_pr.predict( poly.transform(X_test.values) )
# # R²
r2_squared_test_net_pr = mt.r2_score(y_test, y_pred_net_pr_teste)
print("R²:", r2_squared_test_net_pr)
# MSE 
mse_test_net_pr = mt.mean_squared_error(y_test, y_pred_net_pr_teste)
print("MSE", mse_test_net_pr)
# RMSE
rmse_test_net_pr = np.sqrt(mse_test_net_pr)
print("RMSE", rmse_test_net_pr)
# MAE
mae_test_net_pr = mt.mean_absolute_error(y_test, y_pred_net_pr_teste)
print("MAE", mae_test_net_pr)
# MAPE
y_test_flat = y_test.values.ravel()
y_pred_net_pr_teste_flat = y_pred_net_pr_teste.ravel()

mask = y_test_flat != 0
mape_test_net_pr = np.mean(
    np.abs((y_test_flat[mask] - y_pred_net_pr_teste_flat[mask]) / y_test_flat[mask])
)
print("MAPE", mape_test_net_pr)

R²: 0.7487933451150234
MSE 0.06186452304161126
RMSE 0.2487257989063685
MAE 0.1787818525078811
MAPE 0.2096255582360716

# Resultados

## Resultados treinamento

In [66]:
# criar tabela com os resultados da performace dos algorítimos de classificação com dados de treinamento
resultados_train = pd.DataFrame(columns=['Nome_do_algoritmo', 'R2', 'MSE', 'RMSE', 'MAE', 'MAPE'])

# adicionar os resultados à tabela
resultados_train.loc[0] = ['Linear Regression', r2_squared_train, mse_train, rmse_train, mae_train, mape_train]
resultados_train.loc[1] = ['Decision Tree Regressor', r2_squared_train_dt, mse_train_dt, rmse_train_dt, mae_train_dt, mape_train_dt]
resultados_train.loc[2] = ['Random Forest Regressor', r2_squared_train_rf, mse_train_rf, rmse_train_rf, mae_train_rf, mape_train_rf]
resultados_train.loc[3] = ['Polynomial Regression', r2_squared_train_pr, mse_train_pr, rmse_train_pr, mae_train_pr, mape_train_pr]
resultados_train.loc[4] = ['Linear Regression Lasso', r2_squared_train_la, mse_train_la, rmse_train_la, mae_train_la, mape_train_la]
resultados_train.loc[5] = ['Linear Regression Ridge', r2_squared_train_ri, mse_train_ri, rmse_train_ri, mae_train_ri, mape_train_ri]
resultados_train.loc[6] = ['Linear Regression Elastic Net', r2_squared_train_ne, mse_train_ne, rmse_train_ne, mae_train_ne, mape_train_ne]
resultados_train.loc[7] = ['Polynomial Regression Lasso', r2_squared_train_la_pr, mse_train_la_pr, rmse_train_la_pr, mae_train_la_pr, mape_train_la_pr]
resultados_train.loc[8] = ['Polynomial Regression Ridge', r2_squared_train_ri_pr, mse_train_ri_pr, rmse_train_ri_pr, mae_train_ri_pr, mape_train_ri_pr]
resultados_train.loc[9] = ['Polynomial Regression Elastic Net', r2_squared_train_net_pr, mse_train_net_pr, rmse_train_net_pr, mae_train_net_pr, mape_train_net_pr]


# Transforma o MAPE em porcentagem com 3 casas
resultados_train['MAPE'] = resultados_train['MAPE'].apply(lambda x: f"{x:.3f}")
resultados_train['R2'] = resultados_train['R2'].apply(lambda x: f"{x:.3f}")
resultados_train['MSE'] = resultados_train['MSE'].apply(lambda x: f"{x:.3f}")
resultados_train['RMSE'] = resultados_train['RMSE'].apply(lambda x: f"{x:.3f}")
resultados_train['MAE'] = resultados_train['MAE'].apply(lambda x: f"{x:.3f}")

resultados_train = resultados_train.reset_index(drop=True)
resultados_train

                   Nome_do_algoritmo     R2    MSE   RMSE    MAE   MAPE
0                  Linear Regression  0.554  0.110  0.331  0.249  0.267
1            Decision Tree Regressor  0.898  0.025  0.158  0.050  0.058
2            Random Forest Regressor  0.984  0.004  0.063  0.022  0.024
3              Polynomial Regression  0.544  0.112  0.335  0.267  0.316
4            Linear Regression Lasso  0.523  0.117  0.331  0.276  0.306
5            Linear Regression Ridge  0.554  0.110  0.331  0.249  0.267
6      Linear Regression Elastic Net  0.553  0.110  0.331  0.250  0.268
7        Polynomial Regression Lasso  0.718  0.069  0.263  0.190  0.234
8        Polynomial Regression Ridge  0.751  0.061  0.247  0.178  0.209
9  Polynomial Regression Elastic Net  0.741  0.064  0.252  0.180  0.216

## Resultados validação

In [67]:
# criar tabela com os resultados da performace dos algorítimos de classificação com dados de validação
resultados_val = pd.DataFrame(columns=['Nome_do_algoritmo', 'R2', 'MSE', 'RMSE', 'MAE', 'MAPE'])

# adicionar os resultados à tabela
resultados_val.loc[0] = ['Linear Regression', r2_squared_val, mse_val, rmse_val, mae_val, mape_val]
resultados_val.loc[1] = ['Decision Tree Regressor', r2_squared_val_dt, mse_val_dt, rmse_val_dt, mae_val_dt, mape_val_dt]
resultados_val.loc[2] = ['Random Forest Regressor', r2_squared_val_rf, mse_val_rf, rmse_val_rf, mae_val_rf, mape_val_rf]
resultados_val.loc[3] = ['Polynomial Regression', r2_squared_val_pr, mse_val_pr, rmse_val_pr, mae_val_pr, mape_val_pr]
resultados_val.loc[4] = ['Linear Regression Lasso', r2_squared_val_la, mse_val_la, rmse_val_la, mae_val_la, mape_val_la]
resultados_val.loc[5] = ['Linear Regression Ridge', r2_squared_val_ri, mse_val_ri, rmse_val_ri, mae_val_ri, mape_val_ri]
resultados_val.loc[6] = ['Linear Regression Elastic Net', r2_squared_val_ne, mse_val_ne, rmse_val_ne, mae_val_ne, mape_val_ne]
resultados_val.loc[7] = ['Polynomial Regression Lasso', r2_squared_val_la_pr, mse_val_la_pr, rmse_val_la_pr, mae_val_la_pr, mape_val_la_pr]
resultados_val.loc[8] = ['Polynomial Regression Ridge', r2_squared_val_ri_pr, mse_val_ri_pr, rmse_val_ri_pr, mae_val_ri_pr, mape_val_ri_pr]
resultados_val.loc[9] = ['Polynomial Regression Elastic Net', r2_squared_val_net_pr, mse_val_net_pr, rmse_val_net_pr, mae_val_net_pr, mape_val_net_pr]

# Transforma o MAPE em porcentagem com 3 casas
resultados_val['MAPE'] = resultados_val['MAPE'].apply(lambda x: f"{x:.3f}")
resultados_val['R2'] = resultados_val['R2'].apply(lambda x: f"{x:.3f}")
resultados_val['MSE'] = resultados_val['MSE'].apply(lambda x: f"{x:.3f}")
resultados_val['RMSE'] = resultados_val['RMSE'].apply(lambda x: f"{x:.3f}")
resultados_val['MAE'] = resultados_val['MAE'].apply(lambda x: f"{x:.3f}")

resultados_val = resultados_val.reset_index(drop=True)
resultados_val

                   Nome_do_algoritmo     R2    MSE   RMSE    MAE   MAPE
0                  Linear Regression  0.548  0.111  0.333  0.250  0.270
1            Decision Tree Regressor  0.843  0.039  0.197  0.064  0.073
2            Random Forest Regressor  0.885  0.028  0.168  0.060  0.066
3              Polynomial Regression  0.543  0.112  0.335  0.267  0.315
4            Linear Regression Lasso  0.519  0.118  0.344  0.277  0.308
5            Linear Regression Ridge  0.548  0.111  0.333  0.250  0.270
6      Linear Regression Elastic Net  0.547  0.111  0.333  0.251  0.270
7        Polynomial Regression Lasso  0.716  0.070  0.264  0.191  0.235
8        Polynomial Regression Ridge  0.748  0.062  0.249  0.179  0.210
9  Polynomial Regression Elastic Net  0.739  0.064  0.253  0.181  0.217

## Resultados Teste

In [68]:
# criar tabela com os resultados da performace dos algorítimos de classificação com dados de teste
resultados_test = pd.DataFrame(columns=['Nome_do_algoritmo', 'R2', 'MSE', 'RMSE', 'MAE', 'MAPE'])

# adicionar os resultados à tabela
resultados_test.loc[0] = ['Linear Regression', r2_squared_test, mse_test, rmse_test, mae_test, mape_test]
resultados_test.loc[1] = ['Decision Tree Regressor', r2_squared_test_dt, mse_test_dt, rmse_test_dt, mae_test_dt, mape_test_dt]
resultados_test.loc[2] = ['Random Forest Regressor', r2_squared_test_rf, mse_test_rf, rmse_test_rf, mae_test_rf, mape_test_rf]
resultados_test.loc[3] = ['Polynomial Regression', r2_squared_test_pr, mse_test_pr, rmse_test_pr, mae_test_pr, mape_test_pr]
resultados_test.loc[4] = ['Linear Regression Lasso', r2_squared_test_la, mse_test_la, rmse_test_la, mae_test_la, mape_test_la]
resultados_test.loc[5] = ['Linear Regression Ridge', r2_squared_test_ri, mse_test_ri, rmse_test_ri, mae_test_ri, mape_test_ri]
resultados_test.loc[6] = ['Linear Regression Elastic Net', r2_squared_test_ne, mse_test_ne, rmse_test_ne, mae_test_ne, mape_test_ne]
resultados_test.loc[7] = ['Polynomial Regression Lasso', r2_squared_test_la_pr, mse_test_la_pr, rmse_test_la_pr, mae_test_la_pr, mape_test_la_pr]
resultados_test.loc[8] = ['Polynomial Regression Ridge', r2_squared_test_ri_pr, mse_test_ri_pr, rmse_test_ri_pr, mae_test_ri_pr, mape_test_ri_pr]
resultados_test.loc[9] = ['Polynomial Regression Elastic Net', r2_squared_test_net_pr, mse_test_net_pr, rmse_test_net_pr, mae_test_net_pr, mape_test_net_pr]

# Transforma o MAPE em porcentagem com 3 casas
resultados_test['MAPE'] = resultados_test['MAPE'].apply(lambda x: f"{x:.3f}")
resultados_test['R2'] = resultados_test['R2'].apply(lambda x: f"{x:.3f}")
resultados_test['MSE'] = resultados_test['MSE'].apply(lambda x: f"{x:.3f}")
resultados_test['RMSE'] = resultados_test['RMSE'].apply(lambda x: f"{x:.3f}")
resultados_test['MAE'] = resultados_test['MAE'].apply(lambda x: f"{x:.3f}")

resultados_test = resultados_test.reset_index(drop=True)
resultados_test

                   Nome_do_algoritmo     R2    MSE   RMSE    MAE   MAPE
0                  Linear Regression  0.550  0.111  0.333  0.250  0.268
1            Decision Tree Regressor  0.852  0.036  0.191  0.063  0.072
2            Random Forest Regressor  0.889  0.027  0.166  0.056  0.062
3              Polynomial Regression  0.656  0.085  0.291  0.210  0.245
4            Linear Regression Lasso  0.515  0.120  0.346  0.278  0.309
5            Linear Regression Ridge  0.550  0.111  0.333  0.250  0.268
6      Linear Regression Elastic Net  0.549  0.111  0.333  0.251  0.269
7        Polynomial Regression Lasso  0.717  0.070  0.264  0.191  0.233
8        Polynomial Regression Ridge  0.749  0.062  0.249  0.179  0.210
9  Polynomial Regression Elastic Net  0.749  0.062  0.249  0.179  0.210