# Imports

In [38]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn import tree as tr
from sklearn import metrics as mt

from sklearn.metrics import auc
from sklearn.metrics import roc_curve, roc_auc_score

In [39]:
# Dataset
# Carregando dados de treinamento/classificação
X_train =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_treinamento/X_training.csv')
y_train =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_treinamento/y_training.csv')

# Carregando dados de validação/classificação
X_val =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_validacao/X_validation.csv')
y_val =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_validacao/y_validation.csv')

# Carregando dados de teste/Classificação
X_test =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_teste/X_test.csv')
y_test =pd.read_csv('/home/alvaro/Documentos/alvaro/comunidadeds/projetos/ensaios_ml/dataset/ensaio_de_classificacao/dados_teste/y_test.csv')

In [40]:
X_train.head()

,id,customer_type,age,class,flight_distance,inflight_wifi_service,departure_arrival_time_convenient,ease_of_online_booking,gate_location,food_and_drink,...,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,gender_Female,gender_Male,type_of_travel_business_travel,type_of_travel_personal_travel
0,13508,1,0.500000,0.0,0.039580,0.6,0.6,0.6,0.6,1.0,...,0.5,1.00,0.6,0.4,0.000000,0.013848,1.0,0.0,1.0,0.0
1,28874,1,0.243590,0.0,0.205775,0.6,0.4,0.4,0.4,0.6,...,0.5,0.50,0.2,0.6,0.000000,0.000000,0.0,1.0,1.0,0.0
2,21484,0,0.435897,1.0,0.026858,0.6,0.6,0.6,0.2,1.0,...,0.0,1.00,0.6,1.0,0.000000,0.000000,1.0,0.0,1.0,0.0
3,48280,1,0.589744,0.5,0.041397,0.6,1.0,0.6,0.6,0.8,...,0.0,1.00,0.4,0.4,0.029499,0.020772,1.0,0.0,0.0,1.0
4,472,0,0.423077,1.0,0.016559,0.2,0.2,0.2,0.8,0.6,...,1.0,0.75,0.8,0.6,0.021632,0.019782,0.0,1.0,1.0,0.0

# Training

In [41]:
# Algoritmos: 
# Linear Regression, Decision Tree Regressor, Random Forest Regressor, 
# Polinomial Regression, Linear Regression Lasso, Linear Regression Ridge, Linear Regression Elastic Net,
# Polinomial Regression Lasso, Polinomial Regression Ridge e Polinomial Regression Elastic Net
# Métricas de performance: R2, MSE, RMSE, MAE e MAPE

## Linear Regression

In [42]:
# Model Training
lr_model = LinearRegression()
lr_model.fit( X_train, y_train )

LinearRegression()

In [43]:
# Model Performance do treinamento para comparação com o teste
#Previsão sobre os dados de treinamento
y_pred_train = lr_model.predict( X_train )
# # R²
r2_squared_train = mt.r2_score(y_train, y_pred_train)
print("R²:", r2_squared_train)
# MSE 
mse_train = mt.mean_squared_error(y_train, y_pred_train)
print("MSE", mse_train)
# RMSE
rmse_train = np.sqrt(mse_train)
print("RMSE", rmse_train)
# MAE
mae_train = mt.mean_absolute_error(y_train, y_pred_train)
print("MAE", mae_train)
# MAPE
y_train_flat = y_train.values.ravel()
y_pred_train_flat = y_pred_train.ravel()

mask = y_train_flat != 0
mape_train = np.mean(
    np.abs((y_train_flat[mask] - y_pred_train_flat[mask]) / y_train_flat[mask])
)
print("MAPE", mape_train)

R²: 0.553549636106226
MSE 0.1096323327773033
RMSE 0.3311077359067639
MAE 0.24902069470379487
MAPE 0.2667823292751459

In [44]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
model_last_lr = LinearRegression()
model_last_lr.fit( np.concatenate( (X_train, X_val) ), np.concatenate((y_train, y_val)) )

LinearRegression()

In [45]:
# Model Performance da validação para comparação com o teste
#Previsão sobre os dados de validação
y_pred_val = lr_model.predict( X_val )
# # R²
r2_squared_val = mt.r2_score(y_val, y_pred_val)
print("R²:", r2_squared_val)
# MSE 
mse_val = mt.mean_squared_error(y_val, y_pred_val)
print("MSE", mse_val)
# RMSE
rmse_val = np.sqrt(mse_val)
print("RMSE", rmse_val)
# MAE
mae_val = mt.mean_absolute_error(y_val, y_pred_val)
print("MAE", mae_val)
# MAPE
y_val_flat = y_val.values.ravel()
y_pred_val_flat = y_pred_val.ravel()

mask = y_val_flat != 0
mape_val = np.mean(
    np.abs((y_val_flat[mask] - y_pred_val_flat[mask]) / y_val_flat[mask])
)
print("MAPE", mape_train)

R²: 0.547778744051949
MSE 0.11104822157725189
RMSE 0.33323898568032506
MAE 0.24996851952487667
MAPE 0.2667823292751459

In [46]:
# Model Performance validada com os dados de teste e treinada com os dados de treinamento e validação juntos
#Previsão sobre os dados de teste
y_pred_test = model_last_lr.predict( X_test )
# # R²
r2_squared_test = mt.r2_score(y_test, y_pred_test)
print("R²:", r2_squared_test)
# MSE 
mse_test = mt.mean_squared_error(y_test, y_pred_test)
print("MSE", mse_test)
# RMSE
rmse_test = np.sqrt(mse_test)
print("RMSE", rmse_test)
# MAE
mae_test = mt.mean_absolute_error(y_test, y_pred_test)
print("MAE", mae_test)
# MAPE
y_test_flat = y_test.values.ravel()
y_pred_test_flat = y_pred_test.ravel()

mask = y_test_flat != 0
mape_test = np.mean(
    np.abs((y_test_flat[mask] - y_pred_test_flat[mask]) / y_test_flat[mask])
)
print("MAPE", mape_test)

R²: 0.5495195462189956
MSE 0.11093957055194692
RMSE 0.3330759231045482
MAE 0.24996953954986162
MAPE 0.26836840685249835

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

## Decision Tree Regressor

In [47]:
model_train_dt = tr.DecisionTreeRegressor(max_depth=12)
model_train_dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=12)

In [48]:
# Model Performance do treinamento para comparação com os dados de treinamento
#Previsão sobre os dados de treinamento
y_pred_train_dt = model_train_dt.predict( X_train )

# # R²
r2_squared_train_dt = mt.r2_score(y_train, y_pred_train_dt)
print("R²:", r2_squared_train_dt)
# MSE 
mse_train_dt = mt.mean_squared_error(y_train, y_pred_train_dt)
print("MSE", mse_train_dt)
# RMSE
rmse_train_dt = np.sqrt(mse_train_dt)
print("RMSE", rmse_train_dt)
# MAE
mae_train_dt = mt.mean_absolute_error(y_train, y_pred_train_dt)
print("MAE", mae_train_dt)
# MAPE
mape_train_dt = mt.mean_absolute_percentage_error(y_train, y_pred_train_dt)
print("MAPE", mape_train_dt)

R²: 0.8979972201290346
MSE 0.025048255330091914
RMSE 0.15826640619566718
MAE 0.050096510660183835
MAPE 112807313370883.0

In [49]:
#Verificando o melhor valor de max_depth para o Decision Tree Regressor
max_depth_values = range(1, 31)
resultados_dt = []
for i in range(1,31):
    model_val_dt = tr.DecisionTreeRegressor(max_depth=i)
    model_val_dt.fit(X_train, y_train)

    y_pred_val = model_val_dt.predict(X_val)
    
    # Cálculo das métricas
    r2 = mt.r2_score(y_val, y_pred_val)
    mse = mt.mean_squared_error(y_val, y_pred_val)
    rmse = np.sqrt(mse)
    mae = mt.mean_absolute_error(y_val, y_pred_val)
    mape = mt.mean_absolute_percentage_error(y_val, y_pred_val)
    
    # Salva os resultados em um dicionário
    resultados_dt.append({
        'max_depth': i,
        'R2': r2,
        'MSE': mse,
        'RMSE': rmse,
        'MAE': mae,
        'MAPE': mape
    })

# Transforma em DataFrame para facilitar a visualização
dt_resultados = pd.DataFrame(resultados_dt)

# Ordena pelo melhor R² ou menor RMSE
dt_resultados = dt_resultados.sort_values(by='R2', ascending=False)
print(dt_resultados)

    max_depth        R2       MSE      RMSE       MAE          MAPE
11         12  0.841413  0.038943  0.197339  0.064252  1.455293e+14
12         13  0.840040  0.039280  0.198192  0.061322  1.397363e+14
10         11  0.839348  0.039450  0.198620  0.068947  1.567513e+14
13         14  0.836439  0.040164  0.200411  0.059280  1.332725e+14
9          10  0.835328  0.040437  0.201090  0.073756  1.678575e+14
14         15  0.832014  0.041251  0.203103  0.057412  1.296346e+14
8           9  0.830048  0.041734  0.204288  0.079346  1.797923e+14
15         16  0.824674  0.043053  0.207493  0.056810  1.300051e+14
16         17  0.819692  0.044277  0.210420  0.055726  1.269794e+14
7           8  0.816370  0.045093  0.212350  0.087701  1.974983e+14
17         18  0.811862  0.046199  0.214941  0.055538  1.276020e+14
18         19  0.807029  0.047386  0.217684  0.054930  1.246295e+14
19         20  0.803812  0.048176  0.219491  0.054242  1.250634e+14
6           7  0.800579  0.048970  0.221292  0.096639  2.178127e+14
20         21  0.793191  0.050784  0.225354  0.055448  1.279398e+14
21         22  0.789158  0.051775  0.227541  0.055288  1.257742e+14
22         23  0.783920  0.053061  0.230350  0.055618  1.303222e+14
23         24  0.783493  0.053166  0.230577  0.054805  1.267554e+14
24         25  0.782688  0.053364  0.231006  0.054455  1.256970e+14
29         30  0.778268  0.054449  0.233343  0.054516  1.232036e+14
26         27  0.778239  0.054456  0.233358  0.054897  1.248325e+14
25         26  0.778227  0.054459  0.233364  0.055239  1.276091e+14
28         29  0.777644  0.054602  0.233671  0.054752  1.252657e+14
27         28  0.777092  0.054738  0.233961  0.055027  1.269663e+14
5           6  0.773326  0.055663  0.235929  0.110676  2.515697e+14
4           5  0.733173  0.065522  0.255974  0.130202  2.958759e+14
3           4  0.689707  0.076196  0.276036  0.152650  3.462498e+14
2           3  0.644296  0.087347  0.295546  0.176177  3.979204e+14
1           2  0.513391  0.119492  0.345677  0.238302  5.347008e+14
0           1  0.332435  0.163928  0.404881  0.326681  7.347553e+14

In [50]:
# Model Performance da validação para comparação com os dados de treinamento
#Previsão sobre os dados de validação
y_pred_val_dt = model_train_dt.predict( X_val )
# # R²
r2_squared_val_dt = mt.r2_score(y_val, y_pred_val_dt)
print("R²:", r2_squared_val_dt)
# MSE 
mse_val_dt = mt.mean_squared_error(y_val, y_pred_val_dt)
print("MSE", mse_val_dt)
# RMSE
rmse_val_dt= np.sqrt(mse_val_dt)
print("RMSE", rmse_val_dt)
# MAE
mae_val_dt = mt.mean_absolute_error(y_val, y_pred_val_dt)
print("MAE", mae_val_dt)
# MAPE
y_val_flat_dt = y_val.values.ravel()
y_pred_val_dt = y_pred_val_dt.ravel()

mask = y_val_flat_dt != 0
mape_val_dt = np.mean(
    np.abs((y_val_flat_dt[mask] - y_pred_val_dt[mask]) / y_val_flat_dt[mask])
)
print("MAPE", mape_val_dt)

R²: 0.8420171555515151
MSE 0.03879453626950964
RMSE 0.1969632866031374
MAE 0.06410495964717139
MAPE 0.07341648087469262

In [51]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
model_last_dt = tr.DecisionTreeRegressor(max_depth=12)
model_last_dt.fit( np.concatenate( (X_train, X_val) ), np.concatenate((y_train, y_val)) )

DecisionTreeRegressor(max_depth=12)

In [52]:
# Model Performance da validação para comparação com os dados de teste
#Previsão sobre os dados de teste
y_pred_test_dt = model_last_dt.predict( X_test )
# # R²
r2_squared_test_dt = mt.r2_score(y_test, y_pred_test_dt)
print("R²:", r2_squared_test_dt)
# MSE 
mse_test_dt = mt.mean_squared_error(y_test, y_pred_test_dt)
print("MSE", mse_test_dt)
# RMSE
rmse_test_dt= np.sqrt(mse_test_dt)
print("RMSE", rmse_test_dt)
# MAE
mae_test_dt = mt.mean_absolute_error(y_test, y_pred_test_dt)
print("MAE", mae_test_dt)
# MAPE
y_test_flat_dt = y_test.values.ravel()
y_pred_test_dt = y_pred_test_dt.ravel()

mask = y_test_flat_dt != 0
mape_test_dt = np.mean(
    np.abs((y_test_flat_dt[mask] - y_pred_test_dt[mask]) / y_test_flat_dt[mask])
)
print("MAPE", mape_test_dt)

R²: 0.8528618195457015
MSE 0.03623563778269986
RMSE 0.19035660687956132
MAE 0.06276094912455135
MAPE 0.07151834695846904

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but DecisionTreeRegressor was fitted without feature names
  warnings.warn(

## Random Forest Regressor

In [53]:
#Instanciando e treinando a Random Forest Regressor
model_train_rf = RandomForestRegressor(n_estimators=100, max_depth=30)
model_train_rf.fit(X_train, y_train)

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(max_depth=30)

In [54]:
# Model Performance do treinamento para comparação com o teste
#Previsão sobre os dados de treinamento
y_pred_train_rf = model_train_rf.predict( X_train )
# # R²
r2_squared_train_rf = mt.r2_score(y_train, y_pred_train_rf)
print("R²:", r2_squared_train_rf)
# MSE 
mse_train_rf = mt.mean_squared_error(y_train, y_pred_train_rf)
print("MSE", mse_train_rf)
# RMSE
rmse_train_rf = np.sqrt(mse_train_rf)
print("RMSE", rmse_train_rf)
# MAE
mae_train_rf = mt.mean_absolute_error(y_train, y_pred_train_rf)
print("MAE", mae_train_rf)
# MAPE
y_train_flat_rf = y_train.values.ravel()
y_pred_train_rf = y_pred_train_rf.ravel()

mask = y_train_flat_rf != 0
mape_train_rf = np.mean(
    np.abs((y_train_flat_rf[mask] - y_pred_train_rf[mask]) / y_train_flat_rf[mask])
)
print("MAPE", mape_train_rf)

R²: 0.983649897343386
MSE 0.004015003772781044
RMSE 0.06336405742044178
MAE 0.021856080293727684
MAPE 0.024490207182188826

In [55]:
#LOOP para investigar os melhores parâmetros do Random Forest Regressor
# Definição dos parâmetros para investigação
n_estimators_list = [50, 100, 200, 500]
max_depth_list = [5, 10, 20, 30]

resultados = []

for n in n_estimators_list:
    for d in max_depth_list:
        # Inicializa e treina o modelo
        model = RandomForestRegressor(n_estimators=n, max_depth=d, random_state=42, n_jobs=-1)
        model.fit(X_train, y_train)
        
        # Predições
        y_pred = model.predict(X_val)
        
        # Cálculo das métricas
        r2 = mt.r2_score(y_val, y_pred)
        mse = mt.mean_squared_error(y_val, y_pred)
        rmse = np.sqrt(mse)
        mae = mt.mean_absolute_error(y_val, y_pred)
        mape = mt.mean_absolute_percentage_error(y_val, y_pred)
        
        # Salva os resultados em um dicionário
        resultados.append({
            'n_estimators': n,
            'max_depth': d,
            'R2': r2,
            'MSE': mse,
            'RMSE': rmse,
            'MAE': mae,
            'MAPE': mape
        })

# Transforma em DataFrame para facilitar a visualização
df_resultados = pd.DataFrame(resultados)

# Ordena pelo melhor R² ou menor RMSE
df_resultados = df_resultados.sort_values(by='R2', ascending=False)
print(df_resultados)

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

    n_estimators  max_depth        R2       MSE      RMSE       MAE  \
15           500         30  0.886683  0.027826  0.166813  0.059671
11           200         30  0.886339  0.027911  0.167065  0.059619
14           500         20  0.886173  0.027952  0.167187  0.059705
7            100         30  0.885906  0.028017  0.167383  0.059525
10           200         20  0.885727  0.028061  0.167515  0.059697
6            100         20  0.885646  0.028081  0.167574  0.059501
3             50         30  0.884757  0.028299  0.168224  0.059369
2             50         20  0.884485  0.028366  0.168422  0.059433
13           500         10  0.857487  0.034996  0.187072  0.075499
9            200         10  0.857145  0.035080  0.187296  0.075588
5            100         10  0.856732  0.035181  0.187566  0.075664
1             50         10  0.856560  0.035223  0.187679  0.075558
12           500          5  0.734398  0.065222  0.255385  0.130548
8            200          5  0.734367  0.065229  0.255400  0.130639
4            100          5  0.734094  0.065296  0.255531  0.130600
0             50          5  0.733901  0.065344  0.255624  0.130465

            MAPE
15  1.399914e+14
11  1.396647e+14
14  1.389472e+14
7   1.395390e+14
10  1.388166e+14
6   1.384191e+14
3   1.387939e+14
2   1.379398e+14
13  1.708805e+14
9   1.710625e+14
5   1.713166e+14
1   1.710067e+14
12  2.966506e+14
8   2.969207e+14
4   2.968622e+14
0   2.963006e+14

In [56]:
# Model Performance do treinamento para comparação com o teste
#Previsão sobre os dados de validação
y_pred_val_rf = model_train_rf.predict( X_val )
# # R²
r2_squared_val_rf = mt.r2_score(y_val, y_pred_val_rf)
print("R²:", r2_squared_val_rf)
# MSE 
mse_val_rf = mt.mean_squared_error(y_val, y_pred_val_rf)
print("MSE", mse_val_rf)
# RMSE
rmse_val_rf = np.sqrt(mse_val_rf)
print("RMSE", rmse_val_rf)
# MAE
mae_val_rf = mt.mean_absolute_error(y_val, y_pred_val_rf)
print("MAE", mae_val_rf)
# MAPE
y_val_flat_rf = y_val.values.ravel()
y_pred_val_rf = y_pred_val_rf.ravel()

mask = y_val_flat_rf != 0
mape_val_rf = np.mean(
    np.abs((y_val_flat_rf[mask] - y_pred_val_rf[mask]) / y_val_flat_rf[mask])
)
print("MAPE", mape_val_rf)

R²: 0.88552276189663
MSE 0.02811122550134
RMSE 0.1676640256624539
MAE 0.05954677684861644
MAPE 0.06610739436998128

In [57]:
#Modelo validado, agora vamos treinar o modelo com os dados de treinamento e validação juntos para depois testar com os dados de teste
#  Model Training
model_last_rf = RandomForestRegressor(n_estimators=100, max_depth=20)
model_last_rf.fit( np.concatenate( (X_train, X_val) ), np.concatenate((y_train, y_val)) )

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(max_depth=20)

In [58]:
# Model Performance validada com os dados de teste e treinada com os dados de treinamento e validação juntos
#Previsão sobre os dados de teste
y_pred_test_rf = model_last_rf.predict( X_test )
# # R²
r2_squared_test_rf = mt.r2_score(y_test, y_pred_test_rf)
print("R²:", r2_squared_test_rf)
# MSE 
mse_test_rf = mt.mean_squared_error(y_test, y_pred_test_rf)
print("MSE", mse_test_rf)
# RMSE
rmse_test_rf = np.sqrt(mse_test_rf)
print("RMSE", rmse_test_rf)
# MAE
mae_test_rf = mt.mean_absolute_error(y_test, y_pred_test_rf)
print("MAE", mae_test_rf)
# MAPE
y_test_flat_rf = y_test.values.ravel()
y_pred_test_rf = y_pred_test_rf.ravel()

mask = y_test_flat_rf != 0
mape_test_rf = np.mean(
    np.abs((y_test_flat_rf[mask] - y_pred_test_rf[mask]) / y_test_flat_rf[mask])
)
print("MAPE", mape_test_rf)

R²: 0.8879773954168793
MSE 0.02758774446316726
RMSE 0.16609558833144022
MAE 0.056669244917099765
MAPE 0.062249069015965795

/home/alvaro/.pyenv/versions/ensaios_ml/lib/python3.14/site-packages/sklearn/utils/validation.py:2684: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(

# Performance

### Resultados treinamento

In [59]:
# criar tabela com os resultados da performace dos algorítimos de classificação com dados de treinamento
resultados_train = pd.DataFrame(columns=['Nome_do_algoritmo', 'R2', 'MSE', 'RMSE', 'MAE', 'MAPE'])

# adicionar os resultados à tabela
resultados_train.loc[0] = ['Linear Regression', r2_squared_train, mse_train, rmse_train, mae_train, mape_train]
resultados_train.loc[1] = ['Decision Tree Regressor', r2_squared_train_dt, mse_train_dt, rmse_train_dt, mae_train_dt, mape_train_dt]
resultados_train.loc[2] = ['Random Forest Regressor', r2_squared_train_rf, mse_train_rf, rmse_train_rf, mae_train_rf, mape_train_rf]
#resultados_train.loc[3] = ['Polynomial Regression', r2_squared_train_lr, mse_train_lr, rmse_train_lr, mae_train_lr, mape_train_lr]

resultados_train = resultados_train.reset_index(drop=True)
resultados_train

,Nome_do_algoritmo,R2,MSE,RMSE,MAE,MAPE
0,Linear Regression,0.553550,0.109632,0.331108,0.249021,2.667823e-01
1,Decision Tree Regressor,0.897997,0.025048,0.158266,0.050097,1.128073e+14
2,Random Forest Regressor,0.983650,0.004015,0.063364,0.021856,2.449021e-02

### Resultados validação

In [60]:
# criar tabela com os resultados da performace dos algorítimos de classificação com dados de validação
resultados_train = pd.DataFrame(columns=['Nome_do_algoritmo', 'R2', 'MSE', 'RMSE', 'MAE', 'MAPE'])

# adicionar os resultados à tabela
resultados_train.loc[0] = ['Linear Regression', r2_squared_val, mse_val, rmse_val, mae_val, mape_val]
resultados_train.loc[1] = ['Decision Tree Regressor', r2_squared_val_dt, mse_val_dt, rmse_val_dt, mae_val_dt, mape_val_dt]
resultados_train.loc[2] = ['Random Forest Regressor', r2_squared_val_rf, mse_val_rf, rmse_val_rf, mae_val_rf, mape_val_rf]
#resultados_train.loc[3] = ['Polynomial Regression', r2_squared_val_lr, mse_val_lr, rmse_val_lr, mae_val_lr, mape_val_lr]

resultados_train = resultados_train.reset_index(drop=True)
resultados_train

         Nome_do_algoritmo        R2       MSE      RMSE       MAE      MAPE
0        Linear Regression  0.547779  0.111048  0.333239  0.249969  0.269532
1  Decision Tree Regressor  0.842017  0.038795  0.196963  0.064105  0.073416
2  Random Forest Regressor  0.885523  0.028111  0.167664  0.059547  0.066107

## Resultados Teste

In [61]:
# criar tabela com os resultados da performace dos algorítimos de classificação com dados de teste
resultados_train = pd.DataFrame(columns=['Nome_do_algoritmo', 'R2', 'MSE', 'RMSE', 'MAE', 'MAPE'])

# adicionar os resultados à tabela
resultados_train.loc[0] = ['Linear Regression', r2_squared_test, mse_test, rmse_test, mae_test, mape_test]
resultados_train.loc[1] = ['Decision Tree Regressor', r2_squared_test_dt, mse_test_dt, rmse_test_dt, mae_test_dt, mape_test_dt]
resultados_train.loc[2] = ['Random Forest Regressor', r2_squared_test_rf, mse_test_rf, rmse_test_rf, mae_test_rf, mape_test_rf]
#resultados_train.loc[3] = ['Polynomial Regression', r2_squared_lr, mse_lr, rmse_lr, mae_lr, mape_lr]

resultados_train = resultados_train.reset_index(drop=True)
resultados_train

         Nome_do_algoritmo        R2       MSE      RMSE       MAE      MAPE
0        Linear Regression  0.549520  0.110940  0.333076  0.249970  0.268368
1  Decision Tree Regressor  0.852862  0.036236  0.190357  0.062761  0.071518
2  Random Forest Regressor  0.887977  0.027588  0.166096  0.056669  0.062249